name: ladybug-fun-facts
on:
  schedule:
    # 9am, 11am, 1pm, 3pm, 5pm, 7pm, 9pm, 11pm
    # 17   19    21   23   1    3    5    7
    - cron: '0 17,21,3 * * *'
jobs:
  tweet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ladybug-fun-facts

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post Tweet
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python tweet.py

      - name: Commit Files
        run: |
          git config --local user.email "hellstealz@crypto-bugs.com"
          git config --local user.name "GitHub Action"
          git commit -m "posted tweet" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
